#release configuration
#Sat Feb 18 10:31:21 CST 2023
scm.commentPrefix=[maven-release-plugin] 
project.scm.org.apache.rocketmq\:rocketmq-spring-all.tag=HEAD
pushChanges=true
project.rel.org.apache.rocketmq\:rocketmq-spring-boot-parent=2.2.3
project.scm.org.apache.rocketmq\:rocketmq-spring-boot.empty=true
project.scm.org.apache.rocketmq\:rocketmq-spring-all.developerConnection=scm\:git\:git@github.com\:apache/rocketmq-spring.git
scm.tag=rocketmq-spring-all-2.2.3
remoteTagging=true
project.rel.org.apache.rocketmq\:rocketmq-spring-boot=2.2.3
project.scm.org.apache.rocketmq\:rocketmq-spring-all.url=git@github.com\:apache/rocketmq-spring.git
exec.additionalArguments=-Papache-release -DskipTests -P alibaba,signed_release
projectVersionPolicyId=default
project.rel.org.apache.rocketmq\:rocketmq-spring-all=2.2.3
project.dev.org.apache.rocketmq\:rocketmq-spring-boot-parent=2.2.4-SNAPSHOT
scm.url=scm\:git\:git@github.com\:apache/rocketmq-spring.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.dev.org.apache.rocketmq\:rocketmq-spring-all=2.2.4-SNAPSHOT
preparationGoals=clean verify
project.scm.org.apache.rocketmq\:rocketmq-spring-all.connection=scm\:git\:git@github.com\:apache/rocketmq-spring.git
project.scm.org.apache.rocketmq\:rocketmq-spring-boot-starter.empty=true
project.dev.org.apache.rocketmq\:rocketmq-spring-boot-starter=2.2.4-SNAPSHOT
project.scm.org.apache.rocketmq\:rocketmq-spring-boot-parent.empty=true
exec.snapshotReleasePluginAllowed=false
project.dev.org.apache.rocketmq\:rocketmq-spring-boot=2.2.4-SNAPSHOT
completedPhase=end-release
project.rel.org.apache.rocketmq\:rocketmq-spring-boot-starter=2.2.3
